### ISSUE TITLE
iOS 9 Support

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#182]
iOS9 is on the doorstep, we have a list of features to adapt/adopt:

 - [x] Metadata for Objective-C Generics - #177
      - [x] Remove tokens stripping by migrating to Clang 3.7 #227 
 - [x] Research NativeScript for iOS Build Using Bitcode - #184
 - [ ] iOS 9 Support: Bitcode Submission - #225
 - [x] Use a single metadata file - #179
 - [x] Generics in TypeScript definitions - #181
 - [ ] WatchOS metadata availability - #180
 - [x] Research NativeScript for watchOS - #183
