### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by jasssonpet** [NativeScript/ios-runtime#282]
- [ ] Methods with null terminated varargs should not be added in the ios.d.ts
- [ ] Rewriting our tests in TypeScript would keep them up to date
- [ ] TypeScript declarations for NativeScript intrinsics
- [ ] TypeScript declarations for JavaScriptCore intrinsics
- [ ] TypeScript declarations for hardcoded inline functions and variables
- ...
