### ISSUE TITLE
CMake the JSC

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#49]
Use CMake to build the JSC used in NativeScript for iOS.

 - [x] Verify with the AppStore
 - [x] Update build scripts
 - [x] Update Jenkins bulds
 - [x] Pass excessive testing NativeScript (automation tests etc.)
 - [x] Investigate a crash on one of the devices we have
 - [x] Update Web Inspector - #163
 - [ ] JSC unit tests - #50
 - [x] Update the build performance
 - [x] Migrate the `NSDictionary` adapters
 - [x] Update the README.md
 - [ ] Update documentation with ES6 features - #122
 - [ ] Add lib.d.ts with the globals of our JSC version - #218
 - [x] Performance and memory diffs - #185
 - [x] Fix TypeScript inheritance - #178

**Comment by jasssonpet** [comment]
@NativeScript/nativescript-for-ios The new JavaScript version is merged in master.

**Comment by jasssonpet** [comment]
You can use `git config --local submodule.src/webkit.ignore dirty` to speed up git operations:

> Defines under what circumstances "git status" and the diff family show a submodule as modified.

> When set to "all", it will never be considered modified (but it will nonetheless show up in the output of status and commit when it has been staged),

> "dirty" will ignore all changes to the submodules work tree and takes only differences between the HEAD of the submodule and the commit recorded in the superproject into account.

> "untracked" will additionally let submodules with modified tracked files in their work tree show up.

> Using "none" (the default when this option is not set) also shows submodules that have untracked files in their work tree as changed.

**Comment by PanayotCankov** [comment]
There are a few steps left in this issue that are large enough tasks by themselves.
They will be left for some of the upcoming versions.
I am closing the issue.
