### ISSUE TITLE
3rd party static libraries

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#62]
We need to support static libraries added in a NativeScript for iOS project.

One of the use cases is adopting existing codebase that is not available in source form.
We had request for the [MagTek](http://www.magtek.com/support/software/programming_tools/) hardware support. They do distribute officially a static library.

We are not certain for implementation:

 1. Ideally the NativeScript users will use a `library add` like command with the `lib*.a` file, point the headers that declare the exposed APIs and provide additional flags if necessary. Since static libraries does not declare their dependencies the developers may also need to resolve them.

 2. As an alternative we can let the clients set up the Xcode project and link the library themselves as well as set header search paths, and we can try to simply generate metadata for these headers and expect that the static libraries are setup properly.

 3. We can also investigate if we can provide tooling to wrap static libraries in shared frameworks that work with the already existing tooling.

Create small examples using:
 - [x] ~~Static Library~~
 - [x] Static Framework - #141
 - [x] Cocoa pods example - #144
 - [x] Consume Objective-C Code in the Project - #145

[Also we should keep an eye on this issue, and try to satisfy its prerequisites. (pods for example)](https://github.com/NativeScript/NativeScript/issues/25)

Add out of the box support for:
 - [ ] Consuming Objective-C Code in the Project - #146
 - [x] Static Framework added through Plugins
 - [ ] Write an article how to wrap static library into a framework - #147
 - [x] Cocoa pods added through Plugins - #94 

News/Rumors
[Google is embracing CocoaPods to bring its services to iOS developers](http://thenextweb.com/insider/2015/05/28/google-is-embracing-cocoapods-to-bring-its-services-to-ios-developers/)

**Comment by jasssonpet** [comment]
We also need to take care of symbol stripping.

**Comment by raazo** [comment]
Hi Pana,

We have a similiar request for Honeywell Captuvo Sled hardware, please see following link for more info.

https://www.honeywellaidc.com/Captuvo/software/CaptuvoSDK_2.19.742.zip

we require following to use

/SDK/Include/Captuvo.h
/SDK/Lib/libCaptuvoSDK.a

and

ExternalAccessory.framework

Should you require any more info, please let me know.

**Comment by PanayotCankov** [comment]
We have received a question about firebase:
[https://www.firebase.com/docs/ios/](https://www.firebase.com/docs/ios/)
It looks like it is distributed as a static iOS framework (similar to the NativeScript.framework).
The framework contains the tree:
```
$ tree Firebase.framework
Firebase.framework
├── Firebase
├── Headers
└── Versions
    ├── A
    │   ├── Firebase
    │   └── Headers
    │       ├── FAuthData.h
    │       ├── FAuthType.h
    │       ├── FDataSnapshot.h
    │       ├── FEventType.h
    │       ├── FMutableData.h
    │       ├── FQuery.h
    │       ├── FTransactionResult.h
    │       ├── Firebase.h
    │       └── FirebaseServerValue.h
    └── Current
```
The Firebase.h looks like an umbrella header. The Firebase is a fat binary:
```bash
$ lipo -info Firebase
Architectures in the fat file: Firebase are: armv7 armv7s i386 x86_64 arm64 
```

**Comment by leandroz** [comment]
Google Maps iOS SDK is a static framework too. What is the difference between static and dynamic that makes NativeScript not being able to handle the static ones? just curiosity to learn how things are working.

**Comment by PanayotCankov** [comment]
Shared frameworks
 - Can be used in iOS8+
 - Have information about their dependencies
 - Are linked dynamically and need to be signed just like the app executable
 - Can be shared across extensions
 - Are not so popular

Static frameworks
 - Are linked statically.
 - Some C symbols are stripped and can not be used dynamically from JavaScript.
 - Dependencies must be provided by hand. (e.g. SQLite)
 - For static libraries (if not grouped in a framework) headers must be provided by hand.
 - Are overall harder to integrate automatically

NativeScript for iOS **does support static libraries and frameworks internally**. The problem is that the generation of metadata, additional flags, linking problems etc. made the shared frameworks a better candidate to be officially supported for v1.

Static frameworks and libraries and scheduled for v1.1 and will come along with a packaging mechanism. The additional dependencies and flags will probably be expressed in a package.json.

Meanwhile any additional use cases for static libraries are welcomed, since there are multiple ways they are currently distributed.

**Comment by PanayotCankov** [comment]
Here is the [Google Maps SDK for iOS](https://developers.google.com/maps/documentation/ios/start) static framework. Its pretty much the same as the Firebase.

**Comment by leandroz** [comment]
Thanks for the comments @PanayotCankov !

**Comment by PanayotCankov** [comment]
[We have a Cocoa Pods request here](https://www.nativescript.org/blog/using-3rd-party-ios-frameworks-in-your-nativescript-apps#comments).

**Comment by PanayotCankov** [comment]
It only seems convenient to ask the users wrap static libraries that go with headers in a framework.

For example in case you have the libMyLibrary.a and a few headers that go with it (like the [MagTek](http://www.magtek.com/support/software/programming_tools/) request) you can wrap it as:
```
MyLibrary.framework
├── MyLibrary <- libMyLibrary.a with the "lib" prefix and ".a" extension stripped
└── Headers
    ├── MyLibrary.h <- An umbrella header that eventually includes ClassA.h and ClassB.h
    ├── ClassA.h
    └── ClassB.h
```
In any case it seems more convenient to use this convention rather than inventing a home made package.json configuration.

**Comment by PanayotCankov** [comment]
[We have a user for the Facebook API](https://developers.facebook.com/docs/ios/getting-started#startcoding)

As a side-note: the API requires you to plug some of their callbacks in the AppDelegate.

**Comment by ligaz** [comment]
@PanayotCankov What is the current thinking about those callbacks in the AppDelegate? The same problem goes for [Push Notifications](https://github.com/NativeScript/NativeScript/issues/71) as well.

**Comment by fealebenpae** [comment]
@ligaz Perhaps the AppDelegate created by our `application` module should raise iOS-specific events, or provide a hooking mechanism of some sort, so that workflows that need to plug into the AppDelegate can be implemented. Of course, if a developer is not using our `application` module, then they need to create the AppDelegate class themselves and that leaves them free to plug callbacks any way they wish.

**Comment by PanayotCankov** [comment]
As a solution of last resort we support method swizzling, you can swizzle the methods on TNSAppDelegate from the "application" module, however we do **not recommend** it as its quite fragile.

It would be best to use events for these and allow developers to assign the framework handlers. There are already some events exposed, check the application-common.js:
```JavaScript
exports.onUncaughtError = undefined;
exports.onLaunch = undefined;
exports.onSuspend = undefined;
exports.onResume = undefined;
exports.onExit = undefined;
exports.onLowMemory = undefined;
```
However they are platform agnostic and I think we do not expose the native arguments. For example the onLaunch is invoked in applicationDidFinishLaunchingWithOptions, however the iOS application and launchingOptions are not provided as arguments:
``` JavaScript
    TNSAppDelegate.prototype.applicationDidFinishLaunchingWithOptions = function (application, launchOptions) {
        this.window = Window.alloc().initWithFrame(UIScreen.mainScreen().bounds);
        this.window.backgroundColor = UIColor.whiteColor();
        if (exports.onLaunch) {
            exports.onLaunch();
        }
        // .....
        return true;
    };
```

**Comment by FlipOneDev** [comment]
I'm a Javascript developer not familiar at all about so-called "static libraries or frameworks" for the native OS's. I also understand this issue tracker is for iOS stuff.

But what about support for static libraries/frameworks for Android? Should there be such a thing? Is there even such a thing at all as a "static library/framework for Android"?

**Comment by PanayotCankov** [comment]
3rd party static libraries can be consumed through linker flags in the xcconfig along with providing a module map for the header files of these libraries.

**Comment by vijaysharm** [comment]
Hi, I understand this issue is closed, but I'm unable to successfully create a plugin with a static library. Is there a specific directory structure that's required? I feel like [this](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries) doc comes short of giving a full example. Any help here would be appreciated.

**Comment by ivanbuhov** [comment]
@vijaysharm You may find [this comment](https://github.com/NativeScript/ios-runtime/issues/141#issuecomment-315300675) helpful.
