### ISSUE TITLE
iOS Extensions

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/ios-runtime#96]
We need to build and distribute a shared framework out of the NativeScript.framework. This should be relatively easy, we have an internal proof of concept spike that proved that today views work with such framework. It should be distributed in the "tns-ios" npm package. However we should be sensitive for the filesize.

Then we need to provide bootstrappers and instructions how each type of the extension types can be set up manually. Please note that we will not integrate this in the CLI yet.

The most valuable deliverable would be a working WatchKit example. For integration with storyboards we will be ok to require manually written headers for now. In future if we provide our own XML markup for the WatchKit we will be able to generate headers from the XML. Or we can generate headers out of TypeScript declaration files if this would be more familiar to JavaScript developer.

We need to have only one copy of the metadata.

 - [x] [Metadata file should be initialized when the runtime is loading, not with static constructor](https://github.com/NativeScript/ios-runtime/issues/127)
 - [x] [The metadata file should contain extension availability information](https://github.com/NativeScript/ios-runtime/issues/128)
 - [x] Add shared NativeScript framework in the "tns-ios" package
 - [x] Add today view example
 - [x] [Add WatchKit example](https://github.com/NativeScript/ios-runtime/issues/120)
 - [x] Add article to describe how to enable NativeScript extensions by hand in Xcode

**Comment by truongsinh** [comment]
I am sorry but I cannot quite get your idea. Is your "iOS extension" this https://developer.apple.com/app-extensions/ and this https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ ?

**Comment by jasssonpet** [comment]
@truongsinh Yes, the idea is to be able to write native iOS Extensions with NativeScript.

**Comment by truongsinh** [comment]
+1 That is what we have been waiting for a loooong time!

**Comment by jasssonpet** [comment]
You can see a simple working example here: https://github.com/NativeScript/ios-runtime/pull/110/files#diff-2

**Comment by truongsinh** [comment]
Awesome, I though we have to wait, but apparently we can already play around it!

**Comment by truongsinh** [comment]
I know I'm in the wrong repo, but I would like to ask is there a same feature for Android Widget in android-runtime repo? Issue reference would help!

**Comment by jasssonpet** [comment]
ping @slavchev

**Comment by slavchev** [comment]
@truongsinh I created an issue, see https://github.com/NativeScript/android-runtime/issues/69

**Comment by roblav96** [comment]
@jasssonpet @PanayotCankov Where can one find the documentation/conclusion on this research or maybe a demo project for ios extensions? I see it's marked as `done` which is why I'm asking. Thank you! 🍰

**Comment by kspearrin** [comment]
I'm also looking for any docs/guidance on creating app extensions with NativeScript. There doesn't seem to be much.

**Comment by frapaa** [comment]
@PanayotCankov @jasssonpet Is there any recent documentation related to this issue?

**Comment by kspearrin** [comment]
@frapaa The linked examples here don't seem to work anymore. See https://github.com/NativeScript/ios-runtime/issues/929

**Comment by frapaa** [comment]
Yes, I saw that Today example, but the article is from 2015 and not really easy to follow on latest Xcode etc. I was hoping there was a more recent example :) Did you manage to implement an app extension when you where looking into this in March?

**Comment by kspearrin** [comment]
@frapaa  Yes, which is what I mentioned in https://github.com/NativeScript/ios-runtime/issues/929

There is no good documentation for trying to do this at this time. I spent a few days on this unsuccessfully and finally just gave up.

**Comment by frapaa** [comment]
Ok, I'll dig some more. Thanks!

**Comment by erkanarslan** [comment]
We need an up-to-date example and tutorial for this.

**Comment by mbektchiev** [comment]
The current solution is far from perfect and requires quite a lot of manual changes. If you follow the steps in the tutorial, however, it does work. 

That said, we've logged a new issue for app extensions support: https://github.com/NativeScript/nativescript-cli/issues/3965. It is still not planned for implementation but at least can be voted for. 

We would definitely welcome any contributions that can help us reach there!
